# Generated by Django 2.2.4 on 2019-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'account_nick_emotion',
            },
        ),
    ]
