# Generated by Django 2.2.4 on 2019-09-07 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_auto_20190905_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMemberSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_use', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'account_non_member_session',
            },
        ),
    ]
