# Generated by Django 2.2.4 on 2019-09-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_nonmembersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmembersession',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
