# Generated by Django 2.2.4 on 2019-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_key', models.IntegerField(blank=True, default=None, null=True)),
                ('champion_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('champion_brood', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('champion_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('grade1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade4', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade5', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade6', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade7', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade8', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade9', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade10', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade11', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade12', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade13', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade14', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade15', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade16', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade17', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade18', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade19', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('grade20', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
