# Generated by Django 2.2.4 on 2019-09-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='champion',
            table='data_champion',
        ),
    ]
