# Generated by Django 2.2.4 on 2019-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_auto_20190901_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champion_english_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
