# Generated by Django 2.2.4 on 2019-09-02 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_champion_champion_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('summoner_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tier', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('refreshed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankGameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(blank=True, default=None, null=True)),
                ('lose', models.IntegerField(blank=True, default=None, null=True)),
                ('kills', models.IntegerField(blank=True, default=None, null=True)),
                ('deaths', models.IntegerField(blank=True, default=None, null=True)),
                ('assists', models.IntegerField(blank=True, default=None, null=True)),
                ('games', models.IntegerField(blank=True, default=None, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.Champion')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.Summoner')),
            ],
        ),
    ]
