# Generated by Django 2.2.4 on 2019-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_rankgameresult_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankgameresult',
            name='average',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rankgameresult',
            name='winning_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
