# Generated by Django 2.2.4 on 2019-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_auto_20190903_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankgameresult',
            name='winning_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
