# Generated by Django 2.2.4 on 2019-09-07 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_app', '0006_auto_20190903_0218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankgameresult',
            table='data_rank_result',
        ),
        migrations.AlterModelTable(
            name='summoner',
            table='data_summoner',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('ip_addr', models.TextField(blank=True, default=None, max_length=16, null=True)),
                ('nickname', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('written_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.Summoner')),
                ('writer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_comment',
            },
        ),
    ]
