# Generated by Django 2.2.4 on 2019-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_auto_20190907_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.TextField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
