# Generated by Django 2.2.4 on 2019-09-08 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_app', '0009_comment_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.TextField(blank=True, default=None, max_length=16, null=True)),
                ('liked_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('like', models.BooleanField(blank=True, default=False, null=True)),
                ('dislike', models.IntegerField(blank=True, default=False, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comment', to='data_app.Comment')),
                ('liker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_like',
            },
        ),
    ]
