# Generated by Django 2.2.4 on 2019-09-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_auto_20190908_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='reason',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
