# Generated by Django 2.2.4 on 2019-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champion_short',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
