# Generated by Django 2.2.4 on 2019-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_champion_champion_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='summoner',
            name='icon',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='rank',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
