# Generated by Django 2.2.4 on 2019-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0019_auto_20190929_2107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badge',
            table='data_badge',
        ),
    ]
