# Generated by Django 2.2.4 on 2019-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0020_auto_20190929_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='badge1',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='badge2',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='badge3',
        ),
    ]
